apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smile.fullname" . }}-img-crler
  labels:
    {{- include "smile.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.image_crawler.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "smile.name" . }}-img-crler
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "smile.name" . }}-img-crler
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: img-crler
          image: "{{ .Values.image.project }}/{{ .Values.image_crawler.image.repository }}:{{ .Values.image_crawler.image.tag }}"
          imagePullPolicy: {{ .Values.image_crawler.image.pullPolicy | default .Values.image.pullPolicy }}
          command: ["python3"]
          args: ["./rabbitmq_handler.py"]
          env:
            - name: RABBITMQ_HOST
              value: "{{ include "smile.fullname" . }}-rabbitmq"
            - name: QUEUE_NAME
              value: image_crawler
            {{- include "smile.minio.connect" . | nindent 12 }}
            {{- include "smile.email.connect" . | nindent 12 }}
          resources:
            {{- toYaml .Values.image_crawler.resources | nindent 12 }}
      {{- with .Values.image_crawler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.image_crawler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.image_crawler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
