apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smile.fullname" . }}-autophrase
  labels:
    {{- include "smile.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.algorithm_autophrase.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "smile.name" . }}-autophrase
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "smile.name" . }}-autophrase
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: autophrase
          image: "{{ .Values.image.project }}/{{ .Values.algorithm_autophrase.image.repository }}:{{ .Values.algorithm_autophrase.image.tag }}"
          imagePullPolicy: {{ .Values.algorithm_autophrase.image.pullPolicy | default .Values.image.pullPolicy }}
          command: ["/usr/bin/python3"]
          args: ["./rabbitmq_handler.py"]
          env:
            - name: RABBITMQ_HOST
              value: "{{ include "smile.fullname" . }}-rabbitmq"
            - name: QUEUE_NAME
              value: autophrase
            {{- include "smile.minio.connect" . | nindent 12 }}
            {{- include "smile.email.connect" . | nindent 12 }}
          resources:
            {{- toYaml .Values.algorithm_autophrase.resources | nindent 12 }}
      {{- with .Values.algorithm_autophrase.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.algorithm_autophrase.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.algorithm_autophrase.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
