kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "smile.fullname" . }}-tag
  labels:
{{- include "smile.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.smile_server.persistence.size | quote }}
{{- if .Values.smile_server.persistence.storageClass }}
  storageClassName: {{ .Values.smile_server.persistence.storageClass }}
{{- end }}
