apiVersion: v1
kind: Service
metadata:
  name: {{ include "smile.fullname" . }}-server
  labels:
    {{- include "smile.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "smile.name" . }}-server
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.smile_server.service.type }}
  ports:
    - port: {{ .Values.smile_server.service.port }}
      name: server
      targetPort: {{ .Values.smile_server.service.port }}
      protocol: TCP
